### ISSUE TITLE
Unable to login while publishing the chatbot

### ISSUE THREAD

**Issue by kiranvm** [nowfloats/ProjectAna#7]
I setup the chat server in an azure vm as per the specifications mentioned [here ](https://github.com/Kitsune-tools/ProjectANA/blob/master/ANA-CHAT-SERVER-SETUP-README.MD) and was trying to publish a chat bot through studio installed in my desktop computer.

In the chat server connections Server URL was given as http://<<publicIP>PublicIP>:8080 . In the username and password, I gave the username and password  for the docker instance.

Once I click login, it shows the message 'Oops! Unable to login' message.

**Troubleshooting so far**
I checked that docker instance is running with the command 
`sudo docker ps`
Telnet to the public IP with port number from my pc is also working.

Spring Eureka dashboard is loading up if I access the  url <publicIP>:80 from my PC.

**Comment by menneni** [comment]
Since Eureka dashboard is up and you are able to see remaining services through docker ps command, it could be due to issue in configuring server connection in the studio.

'http://:8080' doesn't seem to be like to valid url. Please ensure you to save proper Ana server url in the studio, similar to 'http://localhost:8080' for local environment or 'http://<ip address>:8080' (ex: http://52.156.251.54:8080) for public IP enables VM's.

**Comment by kiranvm** [comment]
Hi,
Thank you for the response.  'http://:8080' was a typo. I have updated the description. Please check.

Ana server URL was given as  'http://public_IP_address_of_vm:8080'

**Comment by menneni** [comment]
Issue was due to MySql version specified in docker-compose.yml, which always pulls latest MySql image. Recently MySql released 8.0 version hence it wasn't working due changes in password encryption.

Now we modified docker-compose.yml to pull MySql 5.7 version to solve the issue.

**Comment by kiranvm** [comment]
Thank you Thej,

We are able to publish chatbots after the change.
